stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: feartango/rancher-demo-maven
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: feartango/rancher-demo-app:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      DOCKER_HOST: tcp://dind.default:2375
      PLUGIN_BUILD_ARGS: VER=${CICD_EXECUTION_SEQUENCE}
      PLUGIN_DAEMON_OFF: "true"
#      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
